In [22]:
len(contours)

12

In [23]:

import cv2
import numpy as np

cap = cv2.VideoCapture('highway.mp4')
frame_width = int( cap.get(cv2.CAP_PROP_FRAME_WIDTH))

frame_height =int( cap.get( cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc('X','V','I','D')

out = cv2.VideoWriter("out.mp4", fourcc, 5.0, (1280,720))

ret, frame1 = cap.read()# 1st frame
ret, frame2 = cap.read() #2nd frame
print(frame1.shape)
while cap.isOpened():
    diff = cv2.absdiff(frame1, frame2)
    gray = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)
    _, thresh = cv2.threshold(blur, 20, 255, cv2.THRESH_BINARY)
    dilated = cv2.dilate(thresh, None, iterations=3)
    contours, _ = cv2.findContours(dilated, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    print(contours)
    for contour in contours:
        (x, y, w, h) =  cv2.boundingRect(contour)

        if cv2.contourArea(contour) < 900:
            continue
        cv2.rectangle(frame1, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(frame1, "Status: {}".format('Movement'), (10, 20),                                                     cv2.FONT_HERSHEY_SIMPLEX,
                    1, (0, 0, 255), 3)
    #cv2.drawContours(frame1, contours, -1, (0, 255, 0), 2)

    image = cv2.resize(frame1, (1280,720))
    out.write(image)
    cv2.imshow("feed", frame1)
    frame1 = frame2
    ret, frame2 = cap.read()#read

    if cv2.waitKey(40) == 27:
        break

cv2.destroyAllWindows()#close window
cap.release()#close camera
out.release()#close when write

(720, 1280, 3)
(array([[[661, 343]],

       [[655, 349]],

       [[655, 367]],

       [[656, 368]],

       [[656, 377]],

       [[657, 378]],

       [[657, 380]],

       [[658, 381]],

       [[658, 382]],

       [[659, 383]],

       [[659, 384]],

       [[660, 385]],

       [[660, 389]],

       [[661, 389]],

       [[662, 390]],

       [[663, 390]],

       [[664, 391]],

       [[672, 391]],

       [[673, 390]],

       [[673, 383]],

       [[672, 382]],

       [[674, 380]],

       [[676, 380]],

       [[676, 373]],

       [[674, 371]],

       [[674, 367]],

       [[675, 366]],

       [[675, 364]],

       [[676, 363]],

       [[676, 351]],

       [[675, 350]],

       [[675, 349]],

       [[671, 345]],

       [[671, 344]],

       [[670, 343]]], dtype=int32), array([[[694, 234]],

       [[694, 240]],

       [[693, 241]],

       [[692, 241]],

       [[691, 242]],

       [[691, 248]],

       [[690, 249]],

       [[689, 249]],

       [[689, 257]],

  

(array([[[660, 357]],

       [[655, 362]],

       [[655, 363]],

       [[654, 364]],

       [[654, 369]],

       [[653, 370]],

       [[653, 377]],

       [[654, 378]],

       [[654, 381]],

       [[655, 382]],

       [[655, 389]],

       [[656, 390]],

       [[656, 395]],

       [[657, 396]],

       [[657, 397]],

       [[658, 398]],

       [[658, 404]],

       [[659, 405]],

       [[661, 405]],

       [[662, 406]],

       [[672, 406]],

       [[673, 405]],

       [[673, 396]],

       [[674, 395]],

       [[674, 382]],

       [[675, 381]],

       [[675, 373]],

       [[676, 372]],

       [[676, 366]],

       [[675, 365]],

       [[675, 364]],

       [[674, 363]],

       [[674, 362]],

       [[671, 359]],

       [[671, 358]],

       [[670, 357]]], dtype=int32), array([[[694, 238]],

       [[694, 244]],

       [[693, 245]],

       [[692, 245]],

       [[692, 251]],

       [[691, 252]],

       [[690, 252]],

       [[689, 253]],

       [[689, 261

(array([[[661, 371]],

       [[659, 373]],

       [[658, 373]],

       [[656, 375]],

       [[655, 375]],

       [[654, 376]],

       [[654, 377]],

       [[653, 378]],

       [[653, 398]],

       [[654, 399]],

       [[654, 405]],

       [[655, 406]],

       [[655, 411]],

       [[656, 412]],

       [[656, 420]],

       [[657, 421]],

       [[658, 421]],

       [[659, 422]],

       [[661, 422]],

       [[664, 425]],

       [[672, 425]],

       [[672, 424]],

       [[673, 423]],

       [[673, 422]],

       [[674, 421]],

       [[674, 413]],

       [[675, 412]],

       [[677, 412]],

       [[677, 406]],

       [[674, 403]],

       [[674, 396]],

       [[675, 395]],

       [[675, 380]],

       [[674, 379]],

       [[674, 377]],

       [[670, 373]],

       [[670, 372]],

       [[668, 372]],

       [[667, 371]]], dtype=int32), array([[[695, 242]],

       [[695, 248]],

       [[694, 249]],

       [[693, 249]],

       [[692, 250]],

       [[692, 256

(array([[[659, 387]],

       [[656, 390]],

       [[655, 390]],

       [[652, 393]],

       [[652, 401]],

       [[651, 402]],

       [[651, 412]],

       [[652, 413]],

       [[652, 414]],

       [[653, 415]],

       [[653, 424]],

       [[654, 425]],

       [[654, 429]],

       [[655, 430]],

       [[655, 431]],

       [[656, 432]],

       [[656, 439]],

       [[657, 440]],

       [[659, 440]],

       [[660, 441]],

       [[661, 441]],

       [[662, 442]],

       [[662, 443]],

       [[663, 444]],

       [[672, 444]],

       [[672, 441]],

       [[673, 440]],

       [[673, 431]],

       [[672, 430]],

       [[673, 429]],

       [[675, 429]],

       [[675, 421]],

       [[674, 420]],

       [[674, 411]],

       [[675, 410]],

       [[675, 396]],

       [[674, 395]],

       [[674, 393]],

       [[668, 387]]], dtype=int32), array([[[  5, 278]],

       [[  4, 279]],

       [[  3, 279]],

       [[  3, 284]],

       [[  2, 285]],

       [[  0, 285

(array([[[676, 472]],

       [[676, 479]],

       [[677, 480]],

       [[677, 481]],

       [[678, 482]],

       [[679, 482]],

       [[680, 483]],

       [[687, 483]],

       [[687, 476]],

       [[684, 473]],

       [[683, 473]],

       [[682, 472]]], dtype=int32), array([[[659, 404]],

       [[658, 405]],

       [[657, 405]],

       [[654, 408]],

       [[653, 408]],

       [[651, 410]],

       [[651, 412]],

       [[650, 413]],

       [[650, 432]],

       [[651, 433]],

       [[651, 440]],

       [[652, 441]],

       [[652, 443]],

       [[653, 444]],

       [[653, 448]],

       [[654, 449]],

       [[654, 451]],

       [[655, 452]],

       [[655, 459]],

       [[657, 461]],

       [[659, 461]],

       [[664, 466]],

       [[671, 466]],

       [[671, 462]],

       [[672, 461]],

       [[672, 450]],

       [[671, 449]],

       [[672, 448]],

       [[675, 448]],

       [[676, 447]],

       [[676, 440]],

       [[675, 439]],

       [[675, 438

(array([[[657, 424]],

       [[654, 427]],

       [[653, 427]],

       [[651, 429]],

       [[651, 430]],

       [[650, 431]],

       [[650, 432]],

       [[649, 433]],

       [[649, 439]],

       [[648, 440]],

       [[648, 450]],

       [[649, 451]],

       [[649, 454]],

       [[650, 455]],

       [[650, 463]],

       [[651, 464]],

       [[651, 469]],

       [[652, 470]],

       [[652, 472]],

       [[653, 473]],

       [[653, 481]],

       [[654, 482]],

       [[654, 483]],

       [[655, 484]],

       [[656, 484]],

       [[657, 485]],

       [[658, 485]],

       [[667, 494]],

       [[668, 494]],

       [[671, 497]],

       [[671, 498]],

       [[672, 498]],

       [[673, 499]],

       [[673, 500]],

       [[674, 501]],

       [[674, 502]],

       [[675, 503]],

       [[675, 504]],

       [[676, 504]],

       [[677, 505]],

       [[684, 505]],

       [[684, 498]],

       [[683, 497]],

       [[683, 495]],

       [[678, 490]],

       [[

(array([[[656, 446]],

       [[655, 447]],

       [[654, 447]],

       [[652, 449]],

       [[651, 449]],

       [[649, 451]],

       [[649, 452]],

       [[648, 453]],

       [[648, 454]],

       [[647, 455]],

       [[647, 462]],

       [[646, 463]],

       [[646, 473]],

       [[647, 474]],

       [[647, 477]],

       [[648, 478]],

       [[648, 485]],

       [[649, 486]],

       [[649, 487]],

       [[650, 488]],

       [[650, 492]],

       [[651, 493]],

       [[651, 497]],

       [[649, 499]],

       [[649, 506]],

       [[650, 507]],

       [[650, 508]],

       [[651, 508]],

       [[652, 509]],

       [[655, 509]],

       [[666, 520]],

       [[666, 521]],

       [[667, 521]],

       [[669, 523]],

       [[669, 524]],

       [[672, 527]],

       [[672, 528]],

       [[674, 530]],

       [[676, 530]],

       [[677, 531]],

       [[682, 531]],

       [[683, 532]],

       [[683, 537]],

       [[690, 537]],

       [[691, 538]],

       [[

(array([[[655, 469]],

       [[651, 473]],

       [[649, 473]],

       [[648, 474]],

       [[647, 474]],

       [[647, 475]],

       [[646, 476]],

       [[646, 478]],

       [[645, 479]],

       [[645, 499]],

       [[646, 500]],

       [[646, 508]],

       [[647, 509]],

       [[647, 513]],

       [[648, 514]],

       [[648, 518]],

       [[649, 519]],

       [[649, 521]],

       [[650, 522]],

       [[650, 523]],

       [[651, 524]],

       [[651, 525]],

       [[650, 526]],

       [[650, 533]],

       [[651, 534]],

       [[651, 535]],

       [[652, 536]],

       [[652, 537]],

       [[654, 537]],

       [[657, 540]],

       [[657, 541]],

       [[666, 550]],

       [[666, 551]],

       [[668, 553]],

       [[668, 554]],

       [[671, 557]],

       [[671, 558]],

       [[674, 561]],

       [[674, 563]],

       [[675, 564]],

       [[676, 564]],

       [[677, 565]],

       [[678, 565]],

       [[681, 568]],

       [[681, 570]],

       [[

In [64]:
import cv2 as cv
import numpy as np
from time import sleep

largura_min = 80
altura_min = 80
offset = 6
pos_linha = 550
delay = 60

detec = []
carros = 0

def pega_centro(x, y, w, h):
    x1 = int(w / 2)
    y1 = int(h / 2)
    cx = x + x1
    cy = y + y1
    return cx, cy  # Fixed the typo here

cap = cv.VideoCapture('highway.mp4')
subtracao = cv.bgsegm.createBackgroundSubtractorMOG(history=12)

while cap.isOpened():
    _, frame1 = cap.read()
    if _ is not True:
        break

    tempo = float(1 / delay)
    sleep(tempo)

    grey = cv.cvtColor(frame1, cv.COLOR_BGR2GRAY)
    blur = cv.GaussianBlur(grey, (3, 3), 5)
    
    img_sub = subtracao.apply(blur)
    dilate = cv.dilate(img_sub, np.ones((9, 9)))
    #kernel = cv.getStructuringElement(cv.MORPH_ELLIPSE, (5, 5))
    #dilatada = cv.morphologyEx(dilate, cv.MORPH_ELLIPSE, kernel)
    cv2.imshow('dilated',dilate)
    contorno, h = cv.findContours(dilate, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

    cv.line(frame1, (25, pos_linha), (1200, pos_linha), (176, 130, 39), 2)
    cv.line(frame1, (25,altura_min ), (1200, largura_min), (0, 0, 39), 2)

    for i, c in enumerate(contorno):
        x, y, w, h = cv.boundingRect(c)
        validar_contorno = (w >= largura_min) and (h >= altura_min)

        #if not validar_contorno:
            #continue
        
        cv.rectangle(frame1, (x, y), (x + w, y + h), (0, 255, 0), 2)
        centro = pega_centro(x, y, w, h)
        detec.append(centro)

    for x, y in detec.copy():  # Use copy to iterate over a copy of the list
        if pos_linha - offset < y < pos_linha + offset:
            carros += 1
            cv.line(frame1, (25, pos_linha), (1200, pos_linha), (0, 0, 255), 2)
            detec.remove((x, y))

    cv.putText(frame1, "VEHICLE COUNT : " + str(carros), (320, 70),
               cv.FONT_HERSHEY_COMPLEX, 2, (0, 0, 255), 4)

    cv.imshow("Vehicle Detection", frame1)

    if cv.waitKey(1) == 27:
        break

cv.destroyAllWindows()
cap.release()
